[package]
name = "eldenring-force-dynamic-shadows"
version = "1.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
region = "3.0.2"
broadsword = { git = "https://github.com/vswarte/broadsword.git" }

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"
